/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp2;

import java.awt.GridLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author ASUS
 */
public class Home extends javax.swing.JFrame {

//    buat properties nya apa aja
        private dbConnection db; // db connection buat conect database
        private Boolean isUpdate = false; // is update buat nentuin cardnya mau di update ato ngga
        private int selectedID; // selectedID buat nunjuk id mana yang mau di hapus atau di delete
        /**
     * Creates new form Register
     */
    public Home() { 
        initComponents();
        db = new dbConnection(); // instansiasi db connection
        refreshpanel(); // menjalankan method refreshpanel untuk mengupdate card mobil dan customer
    }
    
    // method set Panel buat add card mobil di panel utama
    public void setPanel() {
        mainPanel.removeAll(); // remove all buat nge refresh biar kalo abis add / ubah / hapus udah ke update
        mainPanel.setLayout(new GridLayout(0,1)); // setting layout nya
        ResultSet res = db.selectQuery("SELECT * FROM mobil"); // bikin variabel res buat nunjuk ke data yang ada di database
        try {
            // akan trus looping sampai data yang ada di database habis
            while(res.next()){
                // add card mobil
                mainPanel.add(new CardMobil(res.getInt("id_mobil"), res.getString("nama_mobil"),res.getString("plat_nomer"),res.getString("merk_mobil"),res.getString("jenis_mobil"), this));
            }
        } catch (SQLException ex){
            System.out.println(ex.getMessage());
        }
        
        mainPanel.revalidate();
        mainPanel.repaint();
    }
    
    public void refreshpanel(){        
        setPanel(); // menjalankan method set Panel
        setPanel2();
    }
    
    public void setPanel2() {
        mainPanel2.removeAll(); // remove all buat nge refresh biar kalo abis add / ubah / hapus udah ke update
        mainPanel2.setLayout(new GridLayout(0,1)); // setting layout nya
        ResultSet res = db.selectQuery("SELECT * FROM customer"); // bikin variabel res buat nunjuk ke data yang ada di database
        try {
            // akan trus looping sampai data yang ada di database habis
            while(res.next()){
                // add card mobil
                mainPanel2.add(new CardCustomer(res.getInt("id_customer"), res.getString("nama_customer"),res.getString("alamat"),res.getString("nik"), this,res.getInt("id_mobil")));
            }
        } catch (SQLException ex){
            System.out.println(ex.getMessage());
        }
        
        mainPanel2.revalidate();
        mainPanel2.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        jButton_Add = new javax.swing.JButton();
        jButton_Customer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        mainPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(mainPanel);

        jButton_Add.setText("Add Mobil");
        jButton_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddActionPerformed(evt);
            }
        });

        jButton_Customer.setText("Add Data Diri");
        jButton_Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanel2Layout = new javax.swing.GroupLayout(mainPanel2);
        mainPanel2.setLayout(mainPanel2Layout);
        mainPanel2Layout.setHorizontalGroup(
            mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
        );
        mainPanel2Layout.setVerticalGroup(
            mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(mainPanel2);

        jLabel1.setText("Silahkan Pilih Mobil Rental Kesukaan Anda!");

        jLabel2.setText("Daftar Customer dengan mobil yang dirental!!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(82, Short.MAX_VALUE)
                        .addComponent(jButton_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jButton_Customer, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Add)
                    .addComponent(jButton_Customer))
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CustomerActionPerformed
        // TODO add your handling code here:
         insertCustomer rg = new insertCustomer(this.isUpdate, this.selectedID, this);
         rg.setVisible(true);
         rg.pack();
         rg.setLocationRelativeTo(null);
         rg.setDefaultCloseOperation(insertCustomer.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton_CustomerActionPerformed

    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddActionPerformed
         // ketika button add di pencet maka akaun menginstansiasi form insert mobil
         InsertMobil rg = new InsertMobil(this.isUpdate, this.selectedID, this);
         rg.setVisible(true);
         rg.pack();
         rg.setLocationRelativeTo(null);
         rg.setDefaultCloseOperation(InsertMobil.EXIT_ON_CLOSE);// TODO add your handling code here:
    }//GEN-LAST:event_jButton_AddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add;
    private javax.swing.JButton jButton_Customer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mainPanel2;
    // End of variables declaration//GEN-END:variables
}
