/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp2;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ASUS
 */
public class InsertMobil extends javax.swing.JFrame {

    /**
     * Creates new form InsertMobil
     */
    private dbConnection db;
    private Boolean isUpdate;
    private int selectedID;
    private Home home;
    private Imagessss image = new Imagessss();
    private String gambar;
    private File Putu;
    
    public InsertMobil(Boolean is_update, int selected_id, Home homes) {
        initComponents();
        db = new dbConnection();
        this.isUpdate = is_update;
        this.selectedID = selected_id;
        this.home = homes;
        
        if(is_update == true){
            ResultSet res = db.selectQuery("SELECT * FROM mobil where id_mobil=" + selected_id);
            AddMobil.setText("Ubah");
            try {
                if(res.next()){
                    namaMobilField.setText(res.getString("nama_mobil"));
                    platNomerField.setText(res.getString("plat_nomer"));
                    merkMobilField.setText(res.getString("merk_mobil"));
                    jenisMobilField.setText(res.getString("jenis_mobil"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(InsertMobil.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private InsertMobil() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namaMobilField = new javax.swing.JTextField();
        platNomerField = new javax.swing.JTextField();
        merkMobilField = new javax.swing.JTextField();
        jenisMobilField = new javax.swing.JTextField();
        AddMobil = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        Button_foto = new javax.swing.JButton();
        fieldGambar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama Mobil");

        jLabel3.setText("Plat Nomer");

        jLabel4.setText("Merk Mobil");

        jLabel5.setText("Jenis Mobil");

        namaMobilField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaMobilFieldActionPerformed(evt);
            }
        });

        platNomerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platNomerFieldActionPerformed(evt);
            }
        });

        merkMobilField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merkMobilFieldActionPerformed(evt);
            }
        });

        jenisMobilField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisMobilFieldActionPerformed(evt);
            }
        });

        AddMobil.setText("Add");
        AddMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMobilActionPerformed(evt);
            }
        });

        jButton_Cancel.setText("Cancel");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });

        Button_foto.setText("Pilih Foto");
        Button_foto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_fotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Button_foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(platNomerField, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(namaMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(merkMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jenisMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(fieldGambar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(namaMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(platNomerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(merkMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jenisMobilField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddMobil)
                    .addComponent(jButton_Cancel)
                    .addComponent(Button_foto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldGambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jenisMobilFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisMobilFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisMobilFieldActionPerformed

    private void platNomerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platNomerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_platNomerFieldActionPerformed

    private void merkMobilFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merkMobilFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_merkMobilFieldActionPerformed

    private void insertData(){
        int id;
        String nama = namaMobilField.getText();
        String plat = platNomerField.getText();
        String merk = merkMobilField.getText();
        String jenis = jenisMobilField.getText();
        int status = 0;
            Date dNow = new Date();
            SimpleDateFormat ft = new SimpleDateFormat("yyMMddhhmmssMs");
            this.gambar = ft.format(dNow)+"_"+image.getFile().getName();
            uploadImg(this.gambar);

        if(nama.isEmpty() || plat.isEmpty() || merk.isEmpty() || jenis.isEmpty()){
            JOptionPane.showMessageDialog(null, "Silahkan isi data dengan lengkap");
        } else {
            String sql = "INSERT INTO mobil (id_mobil, nama_mobil, plat_nomer, merk_mobil, jenis_mobil, status, gambar) VALUES (null, '"+nama+"', '"+plat+"', '"+merk+"', '"+jenis+"', '"+status+"', '"+this.gambar+"')";
            db.updateQuery(sql);
            JOptionPane.showMessageDialog(null, "data berhasil ditambahkan");    
            dispose();
        }
    }
    
    public void uploadImg(String img){
         try {
            Path copied = Paths.get("src/immmages/"+img);
            Path originalPath = Paths.get(image.getFile().getAbsolutePath());
            Files.copy(originalPath, copied, StandardCopyOption.REPLACE_EXISTING);
          } catch (IOException e) {
              JOptionPane.showMessageDialog(null, e.getMessage());
              e.printStackTrace();
          }
    }
    
    private void updateData(){
        String nama = namaMobilField.getText();
        String plat = platNomerField.getText();
        String merk = merkMobilField.getText();
        String jenis = jenisMobilField.getText();
        this.gambar = fieldGambar.getText();
    
        if(nama.isEmpty() || plat.isEmpty() || merk.isEmpty() || jenis.isEmpty()){
            JOptionPane.showMessageDialog(null, "Silahkan isi data dengan lengkap");
        } else {
            if(image.getFile()!=null)
            {
                if(Putu != null) Putu.delete();
            uploadImg(this.gambar);
            }
            
            String sql = "UPDATE `mobil` SET nama_mobil='" + nama + "', plat_nomer='" + plat + "', merk_mobil='" + merk + "', jenis_mobil='" + jenis + "',gambar='" + this.gambar + "' WHERE id_mobil=" + this.selectedID;
            db.updateQuery(sql);
            JOptionPane.showMessageDialog(null, "data berhasil diubah");    
            dispose();
        }
    }
    
    private void AddMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMobilActionPerformed
      // TODO add your handling code here:
      if (isUpdate == false) {
          insertData();
          this.home.refreshpanel();
      } else {
          updateData();
          this.home.refreshpanel();
      }
    }//GEN-LAST:event_AddMobilActionPerformed

    private void namaMobilFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaMobilFieldActionPerformed
//        namaMobilField.setText("asoy");
    }//GEN-LAST:event_namaMobilFieldActionPerformed

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton_CancelActionPerformed

    private void Button_fotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_fotoActionPerformed
        // TODO add your handling code here:
        image.Browse();
        fieldGambar.setText(image.getPath());
    }//GEN-LAST:event_Button_fotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new InsertMobil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMobil;
    private javax.swing.JButton Button_foto;
    private javax.swing.JTextField fieldGambar;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jenisMobilField;
    private javax.swing.JTextField merkMobilField;
    private javax.swing.JTextField namaMobilField;
    private javax.swing.JTextField platNomerField;
    // End of variables declaration//GEN-END:variables
}
